language: php
php:
  - 5.5
  - 5.6
  - hhvm
  #- nightly
  
services:
  - mysql
  - redis-server
  
script: ./vendor/bin/phpunit
  
before_script:
  #MySQL database init
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -uroot -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost' IDENTIFIED BY 'test';"

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-source --no-interaction

